/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque.telas.Produtos;

import estoque.controladores.ControladorProduto;
import estoque.modelos.Produto;
import estoque.telas.telasMenu.MenuInicial;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FHC
 */
public class ProdutoListagem extends javax.swing.JFrame {

    ArrayList<Produto> listaProdutosGlobal;

    /**
     * Creates new form MecanicoListagem
     */
    public ProdutoListagem() {
        initComponents();
        this.setLocationRelativeTo(null);
        listarProduto();
    }

    public void listarProduto() {

        DefaultTableModel modelo = new DefaultTableModel();
        //atribuindo as colunas da tabela
        modelo.setColumnIdentifiers(new String[]{"Referência", "Fornecedor",
            "Preço Venda", "Estoque Atual", "Aplicação"});
        try {
            ControladorProduto cp = new ControladorProduto();
            this.listaProdutosGlobal = cp.listar();
            for (Produto p : listaProdutosGlobal) {
                modelo.addRow(new String[]{"" + p.getReferencia(), p.getFornecedor().getNomeFantasia(),
                    "R$: " + p.getPrecoVenda(), "" + p.getEstoqueAtual(), p.getAplicacao()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        tabelaProduto.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filtroProdutoTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        alterarMecanicoToggleButton = new javax.swing.JToggleButton();
        removerMecanicoToggleButton = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listagem de Produtos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Filtre pelo nome do produto");

        filtroProdutoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroProdutoTextFieldKeyPressed(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        alterarMecanicoToggleButton.setText("Alterar");
        alterarMecanicoToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarMecanicoToggleButtonActionPerformed(evt);
            }
        });

        removerMecanicoToggleButton.setText("Remover");
        removerMecanicoToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMecanicoToggleButtonActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Voltar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removerMecanicoToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(alterarMecanicoToggleButton)
                        .addGap(525, 525, 525))
                    .addComponent(filtroProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtroProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alterarMecanicoToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removerMecanicoToggleButton)
                        .addComponent(jToggleButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void removerMecanicoToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMecanicoToggleButtonActionPerformed
        // TODO add your handling code here:
        try {
            ControladorProduto cp = new ControladorProduto();
            //Seleciona a linha da coluna.
            int index = tabelaProduto.getSelectedRow();

            if (index >= 0) {
                Produto p = this.listaProdutosGlobal.get(index);

                try {
                    cp.remover(p);
                    JOptionPane.showMessageDialog(rootPane, "Produto Removido com "
                            + "Sucesso");
                    listarProduto();
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(rootPane, "Falha ao remover o"
                            + " Produto");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione um Produto para"
                        + " Remover");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_removerMecanicoToggleButtonActionPerformed

    private void alterarMecanicoToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarMecanicoToggleButtonActionPerformed
        // TODO add your handling code here:
        int index = tabelaProduto.getSelectedRow();

        if (index >= 0) {
            Produto p = this.listaProdutosGlobal.get(index);
            AlterarProdutoForm apf = new AlterarProdutoForm(p, this);
            apf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Produto para"
                    + " Alterar");
        }
    }//GEN-LAST:event_alterarMecanicoToggleButtonActionPerformed

    private void filtroProdutoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroProdutoTextFieldKeyPressed
        // TODO add your handling code here:

        DefaultTableModel modelo = new DefaultTableModel();
        //atribuindo as colunas da tabela
        modelo.setColumnIdentifiers(new String[]{"Referência", "Fornecedor",
            "Preço Venda", "Estoque Atual", "Aplicação"});

        if (filtroProdutoTextField.getText().length() > 0) {
            for (Produto p : listaProdutosGlobal) {
                if (p.getReferencia().toLowerCase().contains(
                        filtroProdutoTextField.getText().toLowerCase())) {
                    modelo.addRow(new String[]{"" + p.getReferencia(), 
                        p.getFornecedor().getNomeFantasia(),
                        "R$: " + p.getPrecoVenda(), "" + p.getEstoqueAtual(), p.getAplicacao()});
                }
            }
            tabelaProduto.setModel(modelo);
        } else {
            listarProduto();
        }
    }//GEN-LAST:event_filtroProdutoTextFieldKeyPressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoListagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton alterarMecanicoToggleButton;
    private javax.swing.JTextField filtroProdutoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton removerMecanicoToggleButton;
    private javax.swing.JTable tabelaProduto;
    // End of variables declaration//GEN-END:variables
}
