/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque.telas.telasFornecedor;

import estoque.controladores.ControladorFornecedor;
import estoque.modelos.Fornecedor;
import estoque.util.Util;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author FHC
 */
public class AlterarFornecedorForm extends javax.swing.JFrame {

    /**
     * Creates new form AlterarClientePessoaJuridicaForm
     */
    private String oldCnpj;
    Fornecedor f;
    FornecedorListagem formPai;

    public AlterarFornecedorForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public AlterarFornecedorForm(Fornecedor f, FornecedorListagem formPai) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.f = f;
        this.formPai = formPai;
        this.carregarCampos(this.f);
    }

    private void buscarCep(String cep) {

        String cepTratado = cep.replace("-", "");
        String url = "http://viacep.com.br/ws/" + cepTratado + "/json/";

        Util e = new Util();
        try {
            JSONObject obj = new JSONObject(e.getHttpGET(url));
            logradouroAlterarPJTextField.setText(obj.getString("logradouro"));
            estadoAlterarPJTextField.setText(obj.getString("uf"));
            cidadeAlterarPJTextField.setText(obj.getString("localidade"));
            bairroAlterarPJTextField.setText((obj.getString("bairro")));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Cep inválido, informe CEP com 8 dígitos");
            System.out.println(ex.getMessage());
        }
    }

    private void carregarCampos(Fornecedor f) {
        try {
            this.oldCnpj = f.getCnpj();
            nomeFantasiaAlterarPJTextField.setText(f.getNomeFantasia());
            cnpjAlterarPJTextField.setText(f.getCnpj());
            razaoSocialAlterarPJFormattedTextField.setText(f.getRazaoSocial());
            emailAlterarPJFormattedTextField.setText(f.getEmail());
            telefonePrincAlterarPJFormattedTextField.setText(f.getTelefonePrincipal());
            telefoneOpcionalAlterarPJFormattedTextField.setText(f.getTelefoneOpcional());
            cepAlterarPJFormattedTextField.setText(f.getCep());
            buscarCep(f.getCep());
            responsaveisTextField.setText(f.getNomeResponsaveis());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void limparCampos() {
        try {
            nomeFantasiaAlterarPJTextField.setText("");
            razaoSocialAlterarPJFormattedTextField.setText("");
            cnpjAlterarPJTextField.setText("");
            cepAlterarPJFormattedTextField.setText("");
            logradouroAlterarPJTextField.setText("");
            estadoAlterarPJTextField.setText("");
            cidadeAlterarPJTextField.setText("");
            bairroAlterarPJLabel.setText("");
            emailAlterarPJFormattedTextField.setText("");
            telefonePrincAlterarPJFormattedTextField.setText("");
            telefoneOpcionalAlterarPJFormattedTextField.setText("");
            responsaveisTextField.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeFantasiaAlterarPJLabel = new javax.swing.JLabel();
        nomeFantasiaAlterarPJTextField = new javax.swing.JTextField();
        cnpjAlterarPJLabel = new javax.swing.JLabel();
        cnpjAlterarPJTextField = new javax.swing.JFormattedTextField(new Util().mascara("##.###.##"
            + "#/####-##"));
    razaoSocialAlterarPJLabel = new javax.swing.JLabel();
    emailAlterarPJLabel = new javax.swing.JLabel();
    emailAlterarPJFormattedTextField = new javax.swing.JFormattedTextField();
    razaoSocialAlterarPJFormattedTextField = new javax.swing.JFormattedTextField();
    telefonePrincAlterarPJLabel = new javax.swing.JLabel();
    telefonePrincAlterarPJFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel2 = new javax.swing.JLabel();
    telefoneOpcionalAlterarPJFormattedTextField = new javax.swing.JFormattedTextField();
    cepAlterarPJLabel = new javax.swing.JLabel();
    cepAlterarPJFormattedTextField = new javax.swing.JFormattedTextField();
    logradouroAlterarPJLabel = new javax.swing.JLabel();
    logradouroAlterarPJTextField = new javax.swing.JTextField();
    cidadeAlterarPJLabel = new javax.swing.JLabel();
    cidadeAlterarPJTextField = new javax.swing.JTextField();
    bairroAlterarPJLabel = new javax.swing.JLabel();
    bairroAlterarPJTextField = new javax.swing.JTextField();
    estadoAlterarPJLabel = new javax.swing.JLabel();
    estadoAlterarPJTextField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    responsaveisTextField = new javax.swing.JTextField();
    limparFormularioAlterarPJButton = new javax.swing.JButton();
    alterarPJButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setText("Alterar dados do Fornecedor");

    nomeFantasiaAlterarPJLabel.setText("Nome Fantasia");

    cnpjAlterarPJLabel.setText("Cnpj");

    cnpjAlterarPJTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cnpjAlterarPJTextFieldActionPerformed(evt);
        }
    });

    razaoSocialAlterarPJLabel.setText("Razão Social");

    emailAlterarPJLabel.setText("Email");

    emailAlterarPJFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            emailAlterarPJFormattedTextFieldFocusLost(evt);
        }
    });
    emailAlterarPJFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            emailAlterarPJFormattedTextFieldActionPerformed(evt);
        }
    });

    telefonePrincAlterarPJLabel.setText("Telefone Principal");

    telefonePrincAlterarPJFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            telefonePrincAlterarPJFormattedTextFieldKeyTyped(evt);
        }
    });

    jLabel2.setText("Telefone Opicional");

    telefoneOpcionalAlterarPJFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            telefoneOpcionalAlterarPJFormattedTextFieldKeyTyped(evt);
        }
    });

    cepAlterarPJLabel.setText("Cep");

    cepAlterarPJFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            cepAlterarPJFormattedTextFieldFocusLost(evt);
        }
    });

    logradouroAlterarPJLabel.setText("Logradouro");

    logradouroAlterarPJTextField.setEnabled(false);

    cidadeAlterarPJLabel.setText("Cidade");

    cidadeAlterarPJTextField.setEnabled(false);

    bairroAlterarPJLabel.setText("Bairro");

    bairroAlterarPJTextField.setEnabled(false);

    estadoAlterarPJLabel.setText("Estado");

    estadoAlterarPJTextField.setEnabled(false);

    jLabel3.setText("Nome dos Responsáveis");

    limparFormularioAlterarPJButton.setText("Limpar Formúlario");
    limparFormularioAlterarPJButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            limparFormularioAlterarPJButtonActionPerformed(evt);
        }
    });

    alterarPJButton.setText("Alterar Fornecedor");
    alterarPJButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            alterarPJButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cepAlterarPJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logradouroAlterarPJLabel)
                        .addComponent(cepAlterarPJLabel))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(responsaveisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(estadoAlterarPJLabel)
                .addComponent(limparFormularioAlterarPJButton)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(telefonePrincAlterarPJLabel)
                        .addComponent(telefonePrincAlterarPJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeFantasiaAlterarPJLabel)
                        .addComponent(nomeFantasiaAlterarPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(razaoSocialAlterarPJLabel)
                        .addComponent(razaoSocialAlterarPJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cidadeAlterarPJLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cidadeAlterarPJTextField)
                            .addComponent(estadoAlterarPJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cnpjAlterarPJTextField)
                        .addComponent(bairroAlterarPJTextField)
                        .addComponent(emailAlterarPJFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefoneOpcionalAlterarPJFormattedTextField)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bairroAlterarPJLabel)
                                .addComponent(jLabel2)
                                .addComponent(emailAlterarPJLabel)
                                .addComponent(cnpjAlterarPJLabel))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alterarPJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logradouroAlterarPJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(29, 29, 29))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(41, 41, 41))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nomeFantasiaAlterarPJLabel)
                .addComponent(cnpjAlterarPJLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nomeFantasiaAlterarPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cnpjAlterarPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(razaoSocialAlterarPJLabel)
                .addComponent(emailAlterarPJLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(razaoSocialAlterarPJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailAlterarPJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(telefonePrincAlterarPJLabel)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(telefonePrincAlterarPJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(telefoneOpcionalAlterarPJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cepAlterarPJLabel)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(cepAlterarPJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(logradouroAlterarPJLabel))
                .addComponent(responsaveisTextField))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(logradouroAlterarPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cidadeAlterarPJLabel)
                .addComponent(bairroAlterarPJLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cidadeAlterarPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bairroAlterarPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(estadoAlterarPJLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(estadoAlterarPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(limparFormularioAlterarPJButton)
                .addComponent(alterarPJButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cnpjAlterarPJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjAlterarPJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjAlterarPJTextFieldActionPerformed

    private void emailAlterarPJFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAlterarPJFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAlterarPJFormattedTextFieldActionPerformed

    private void limparFormularioAlterarPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparFormularioAlterarPJButtonActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_limparFormularioAlterarPJButtonActionPerformed

    private void cepAlterarPJFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepAlterarPJFormattedTextFieldFocusLost
        // TODO add your handling code here:
        buscarCep(cepAlterarPJFormattedTextField.getText());
    }//GEN-LAST:event_cepAlterarPJFormattedTextFieldFocusLost

    private void alterarPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarPJButtonActionPerformed
        // TODO add your handling code here:
        try {
            ControladorFornecedor cf = new ControladorFornecedor();
            Fornecedor f = new Fornecedor();

            f.setNomeFantasia(nomeFantasiaAlterarPJTextField.getText());
            f.setCnpj(cnpjAlterarPJTextField.getText());
            f.setRazaoSocial(razaoSocialAlterarPJFormattedTextField.getText());
            f.setEmail(emailAlterarPJFormattedTextField.getText());
            f.setTelefonePrincipal(telefonePrincAlterarPJFormattedTextField.getText());
            f.setTelefoneOpcional(telefoneOpcionalAlterarPJFormattedTextField.getText());
            f.setCep(cepAlterarPJFormattedTextField.getText());
            f.setLogradouro(logradouroAlterarPJTextField.getText());
            f.setCidade(cidadeAlterarPJTextField.getText());
            f.setBairro(bairroAlterarPJTextField.getText());
            f.setEstado(estadoAlterarPJTextField.getText());
            f.setNomeResponsaveis(responsaveisTextField.getText());

            cf.atualizar(f, this.oldCnpj);
            JOptionPane.showMessageDialog(rootPane, "Fornecedor Atualizado com"
                    + " Sucesso");
            this.formPai.listarFornecedor();
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_alterarPJButtonActionPerformed

    private void emailAlterarPJFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailAlterarPJFormattedTextFieldFocusLost
        // TODO add your handling code here:
        String email = emailAlterarPJFormattedTextField.getText().toLowerCase();
        emailAlterarPJFormattedTextField.setText(email);
    }//GEN-LAST:event_emailAlterarPJFormattedTextFieldFocusLost

    private void telefonePrincAlterarPJFormattedTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonePrincAlterarPJFormattedTextFieldKeyTyped
        // TODO add your handling code here:
        char telefonePrinc = evt.getKeyChar();

        if (!((telefonePrincAlterarPJFormattedTextField.getText().length() <= 10) && (telefonePrinc >= '0') && (telefonePrinc <= '9')
                || (telefonePrinc == KeyEvent.VK_BACK_SPACE)
                || (telefonePrinc == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_telefonePrincAlterarPJFormattedTextFieldKeyTyped

    private void telefoneOpcionalAlterarPJFormattedTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneOpcionalAlterarPJFormattedTextFieldKeyTyped
        // TODO add your handling code here:
        char telefoneOpcional = evt.getKeyChar();

        if (!((telefoneOpcionalAlterarPJFormattedTextField.getText().length() <= 10) && (telefoneOpcional >= '0') && (telefoneOpcional <= '9')
                || (telefoneOpcional == KeyEvent.VK_BACK_SPACE)
                || (telefoneOpcional == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_telefoneOpcionalAlterarPJFormattedTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarFornecedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarFornecedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarFornecedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarFornecedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarFornecedorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarPJButton;
    private javax.swing.JLabel bairroAlterarPJLabel;
    private javax.swing.JTextField bairroAlterarPJTextField;
    private javax.swing.JFormattedTextField cepAlterarPJFormattedTextField;
    private javax.swing.JLabel cepAlterarPJLabel;
    private javax.swing.JLabel cidadeAlterarPJLabel;
    private javax.swing.JTextField cidadeAlterarPJTextField;
    private javax.swing.JLabel cnpjAlterarPJLabel;
    private javax.swing.JTextField cnpjAlterarPJTextField;
    private javax.swing.JFormattedTextField emailAlterarPJFormattedTextField;
    private javax.swing.JLabel emailAlterarPJLabel;
    private javax.swing.JLabel estadoAlterarPJLabel;
    private javax.swing.JTextField estadoAlterarPJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limparFormularioAlterarPJButton;
    private javax.swing.JLabel logradouroAlterarPJLabel;
    private javax.swing.JTextField logradouroAlterarPJTextField;
    private javax.swing.JLabel nomeFantasiaAlterarPJLabel;
    private javax.swing.JTextField nomeFantasiaAlterarPJTextField;
    private javax.swing.JFormattedTextField razaoSocialAlterarPJFormattedTextField;
    private javax.swing.JLabel razaoSocialAlterarPJLabel;
    private javax.swing.JTextField responsaveisTextField;
    private javax.swing.JFormattedTextField telefoneOpcionalAlterarPJFormattedTextField;
    private javax.swing.JFormattedTextField telefonePrincAlterarPJFormattedTextField;
    private javax.swing.JLabel telefonePrincAlterarPJLabel;
    // End of variables declaration//GEN-END:variables
}
