/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque.telas.clienteTelas;

import estoque.controladores.ControladorClienteFisico;
import estoque.controladores.ControladorClientePessoaJuridica;
import estoque.modelos.ClienteFisico;
import estoque.modelos.ClientePessoaJuridica;
import estoque.util.Util;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author EWalker
 */
public class clientesForm extends javax.swing.JFrame {

    /**
     * Creates new form FormGeral
     */
    public clientesForm() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    private void limparCampos() {
        nomeClienteTextField.setText("");
        cpfFormattedTextField.setText("");
        nomeFantasiaTextField.setText("");
        razaoSocialTextField.setText("");
        cnpjFormattedTextField.setText("");
        cepFormattedTextField.setText("");
        logradouroTextField.setText("");
        estadoTextField.setText("");
        cidadeTextField.setText("");
        bairroTextField.setText("");
        emailTextField.setText("");
        telefonePrincipalTextField.setText("");
        telefoneOpcionalTextField.setText("");
        numeroTextField.setText("");
    }

    public void buscarCep(String cep) {

        //Definindo a url 
        String url = "http://viacep.com.br/ws/" + cep + "/json/";

        //Criando o objeto Json para receber os dados
    }

    private void camposClientesAtivarLimparClienteJuridico() {

        nomeClienteTextField.setEnabled(true);
        cpfFormattedTextField.setEnabled(true);
        nomeFantasiaTextField.setText("");
        nomeFantasiaTextField.setEnabled(false);
        cnpjFormattedTextField.setText("");
        cnpjFormattedTextField.setEnabled(false);
        razaoSocialTextField.setText("");
        razaoSocialTextField.setEnabled(false);

    }

    private void camposJuridicoAtivarLimparClienteFisico() {

        nomeFantasiaTextField.setEnabled(true);
        cnpjFormattedTextField.setEnabled(true);
        razaoSocialTextField.setEnabled(true);

        nomeClienteTextField.setText("");
        nomeClienteTextField.setEnabled(false);
        cpfFormattedTextField.setText("");
        cpfFormattedTextField.setEnabled(false);
    }

    private void selecionarTipoCliente() {

        if (clienteFisicoButton.isSelected()) {

            camposClientesAtivarLimparClienteJuridico();

        } else if (juridicoFisicoButton.isSelected()) {

            camposJuridicoAtivarLimparClienteFisico();

        }

    }

    private void colocarMascara() {

        if (clienteFisicoButton.isSelected()) {

            nomeFantasiaTextField.setEnabled(false);
            cnpjFormattedTextField.setEnabled(false);
            razaoSocialTextField.setEnabled(false);

        } else if (juridicoFisicoButton.isSelected()) {

            /*  cpfOrCnpjFormattedField.setVisible(false);
            nomeClienteLabel.setText(("Nome Fantasia"));
            cpfOrCnpjFormattedField.setText("");
            cpfOrCnpjFormattedField = new javax.swing.JFormattedTextField(mascara("##.###.#"
                    + "##/####-##"));*/
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoClienteButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        clienteFisicoButton = new javax.swing.JRadioButton();
        juridicoFisicoButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        nomeClienteTextField = new javax.swing.JTextField();
        nomeClienteLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        nomeFantasiaLabel = new javax.swing.JLabel();
        nomeFantasiaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cpfFormattedTextField = new javax.swing.JFormattedTextField(new Util().mascara("###.###.###-##"));
        cnpjFormattedTextField = new javax.swing.JFormattedTextField(new Util().mascara("##.###.##"
            + "#/####-##"));
    razaoSocialLabel = new javax.swing.JLabel();
    razaoSocialTextField = new javax.swing.JTextField();
    emailLabel = new javax.swing.JLabel();
    emailTextField = new javax.swing.JTextField();
    telefonePrincipalLabel = new javax.swing.JLabel();
    telefonePrincipalTextField = new javax.swing.JTextField();
    telefoneOpcionalTextField = new javax.swing.JTextField();
    telefoneOpcionalLabel = new javax.swing.JLabel();
    cepLabel = new javax.swing.JLabel();
    cepFormattedTextField = new javax.swing.JFormattedTextField(new Util().mascara("#####-###"));
    logradouroTextField = new javax.swing.JTextField();
    logradouroLabel = new javax.swing.JLabel();
    estadoLabel = new javax.swing.JLabel();
    estadoTextField = new javax.swing.JTextField();
    cidadeTextField = new javax.swing.JTextField();
    bairroTextField = new javax.swing.JTextField();
    bairroLabel = new javax.swing.JLabel();
    cadastrarButton = new javax.swing.JToggleButton();
    jToggleButton2 = new javax.swing.JToggleButton();
    numeroLabel = new javax.swing.JLabel();
    numeroTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    cidadeLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel1.setText("Tipo do Cliente");

    tipoClienteButton.add(clienteFisicoButton);
    clienteFisicoButton.setSelected(true);
    clienteFisicoButton.setLabel("Físico");
    clienteFisicoButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            clienteFisicoButtonActionPerformed(evt);
        }
    });

    tipoClienteButton.add(juridicoFisicoButton);
    juridicoFisicoButton.setText("Jurídico");
    juridicoFisicoButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            juridicoFisicoButtonActionPerformed(evt);
        }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel2.setText("Cadastrar Cliente");

    nomeClienteTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nomeClienteTextFieldActionPerformed(evt);
        }
    });

    nomeClienteLabel.setText("Nome do Cliente*");

    cpfLabel.setText("Cpf*");

    nomeFantasiaLabel.setText("Nome Fantasia*");

    nomeFantasiaTextField.setEnabled(false);
    nomeFantasiaTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nomeFantasiaTextFieldActionPerformed(evt);
        }
    });

    jLabel3.setText("Cnpj*");

    cpfFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            cpfFormattedTextFieldFocusLost(evt);
        }
    });

    cnpjFormattedTextField.setEnabled(false);
    cnpjFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cnpjFormattedTextFieldActionPerformed(evt);
        }
    });

    razaoSocialLabel.setText("Razão Social*");

    razaoSocialTextField.setEnabled(false);
    razaoSocialTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            razaoSocialTextFieldActionPerformed(evt);
        }
    });

    emailLabel.setText("E-mail*");

    emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            emailTextFieldFocusLost(evt);
        }
    });

    telefonePrincipalLabel.setText("Telefone Principal*");

    telefonePrincipalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            telefonePrincipalTextFieldKeyTyped(evt);
        }
    });

    telefoneOpcionalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            telefoneOpcionalTextFieldKeyTyped(evt);
        }
    });

    telefoneOpcionalLabel.setText("Telefone Opcional");

    cepLabel.setText("Cep*");

    cepFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            cepFormattedTextFieldFocusLost(evt);
        }
    });

    logradouroTextField.setEnabled(false);
    logradouroTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logradouroTextFieldActionPerformed(evt);
        }
    });

    logradouroLabel.setText("Logradouro");

    estadoLabel.setText("Estado");

    estadoTextField.setEnabled(false);
    estadoTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            estadoTextFieldActionPerformed(evt);
        }
    });

    cidadeTextField.setEnabled(false);
    cidadeTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cidadeTextFieldActionPerformed(evt);
        }
    });

    bairroTextField.setEnabled(false);

    bairroLabel.setText("Bairro");

    cadastrarButton.setText("Cadastrar Cliente");
    cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarButtonActionPerformed(evt);
        }
    });

    jToggleButton2.setText("Limpar Formulário");
    jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton2ActionPerformed(evt);
        }
    });

    numeroLabel.setText("Número");

    numeroTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            numeroTextFieldKeyTyped(evt);
        }
    });

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(153, 153, 0));
    jLabel5.setText("* Campos com asterisco são obrigatórios");

    cidadeLabel.setText("Cidade");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailLabel)
                                .addComponent(telefonePrincipalLabel)
                                .addComponent(telefonePrincipalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeClienteLabel)
                                    .addComponent(cpfLabel)
                                    .addComponent(clienteFisicoButton)
                                    .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(telefoneOpcionalLabel)
                                    .addComponent(telefoneOpcionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeClienteTextField)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cnpjFormattedTextField)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(juridicoFisicoButton)
                                            .addGap(178, 178, 178))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomeFantasiaLabel)
                                        .addComponent(nomeFantasiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGap(20, 20, 20))
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jToggleButton2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(279, 279, 279)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(razaoSocialTextField)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(razaoSocialLabel))
                            .addGap(0, 9, Short.MAX_VALUE)))
                    .addGap(18, 18, 18)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(64, 64, 64))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(logradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cepLabel)
                            .addComponent(logradouroLabel)
                            .addComponent(estadoLabel)
                            .addComponent(bairroLabel)
                            .addComponent(numeroLabel)
                            .addComponent(numeroTextField)
                            .addComponent(bairroTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(cidadeTextField)
                            .addComponent(estadoTextField)
                            .addComponent(cepFormattedTextField))
                        .addComponent(cidadeLabel))
                    .addGap(0, 0, Short.MAX_VALUE))))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(220, 220, 220))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(80, 80, 80)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clienteFisicoButton)
                        .addComponent(juridicoFisicoButton))
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeClienteLabel)
                        .addComponent(nomeFantasiaLabel)
                        .addComponent(cepLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeFantasiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cepFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfLabel)
                        .addComponent(jLabel3)
                        .addComponent(logradouroLabel)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jLabel1)))
            .addGap(3, 3, 3)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cnpjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(logradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(razaoSocialLabel)
                        .addComponent(estadoLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(estadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(razaoSocialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailLabel)
                        .addComponent(cidadeLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telefonePrincipalLabel)
                        .addComponent(bairroLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(telefonePrincipalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(telefoneOpcionalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeroLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefoneOpcionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(47, 47, 47)
                    .addComponent(jLabel5)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(245, 301, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40))))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteFisicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteFisicoButtonActionPerformed
        // TODO add your handling code here:
        selecionarTipoCliente();

    }//GEN-LAST:event_clienteFisicoButtonActionPerformed

    private void juridicoFisicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juridicoFisicoButtonActionPerformed
        // TODO add your handling code here:

        selecionarTipoCliente();

    }//GEN-LAST:event_juridicoFisicoButtonActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        limparCampos();

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void cepFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepFormattedTextFieldFocusLost
        // TODO add your handling code here:

        String cepTratado = cepFormattedTextField.getText().replace("-", "");
        String url = "http://viacep.com.br/ws/" + cepTratado + "/json/";

        Util e = new Util();
        try {
            JSONObject obj = new JSONObject(e.getHttpGET(url));
            logradouroTextField.setText(obj.getString("logradouro"));
            estadoTextField.setText(obj.getString("uf"));
            cidadeTextField.setText(obj.getString("localidade"));
            bairroTextField.setText((obj.getString("bairro")));

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(rootPane, "Cep inválido, informe outro!");
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_cepFormattedTextFieldFocusLost

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        
        ClienteFisico c = new ClienteFisico();
        ClientePessoaJuridica pj = new ClientePessoaJuridica();
        
        pj.setTipo(2);
        c.setTipo(2);
        
        if (clienteFisicoButton.isSelected()) {

            c.setNome(nomeClienteTextField.getText());
            c.setCpf(cpfFormattedTextField.getText());
            c.setEmail(emailTextField.getText());
            c.setTelefonePrinc(telefonePrincipalTextField.getText());
            c.setTelefoneOpc(telefoneOpcionalTextField.getText());
            c.setCep(cepFormattedTextField.getText());
            c.setLogradouro(logradouroTextField.getText());
            c.setEstado(estadoTextField.getText());
            c.setCidade(cidadeTextField.getText());
            c.setBairro(bairroTextField.getText());
            c.setNumero(numeroTextField.getText());
            c.setTipo(0);

            ControladorClienteFisico ccf = new ControladorClienteFisico();
            try {
                ccf.cadastrar(c, pj);
                JOptionPane.showMessageDialog(rootPane, "Cliente Pessoa Física"
                        + " cadastrado com sucesso!");
                limparCampos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }

        if (juridicoFisicoButton.isSelected()) {

            pj.setCnpj(cnpjFormattedTextField.getText());
            pj.setNomeFantasia(nomeFantasiaTextField.getText());
            pj.setRazaoSocial(razaoSocialTextField.getText());
            pj.setEmail(emailTextField.getText());
            pj.setTelefonePrinc(telefonePrincipalTextField.getText());
            pj.setTelefoneOpc(telefoneOpcionalTextField.getText());
            pj.setCep(cepFormattedTextField.getText());
            pj.setLogradouro(logradouroTextField.getText());
            pj.setEstado(estadoTextField.getText());
            pj.setCidade(cidadeTextField.getText());
            pj.setBairro(bairroTextField.getText());
            pj.setNumero(numeroTextField.getText());
            pj.setTipo(1);

            ControladorClientePessoaJuridica ccpj = new ControladorClientePessoaJuridica();
            try {
                ccpj.cadastrar(c, pj);
                JOptionPane.showMessageDialog(rootPane, "Cliente Pessoa Juridica"
                        + " cadastrado com sucesso");
                limparCampos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }

        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed


    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        // TODO add your handling code here:
        String email = emailTextField.getText().toLowerCase();
        emailTextField.setText(email);

    }//GEN-LAST:event_emailTextFieldFocusLost

    private void cnpjFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjFormattedTextFieldActionPerformed

    private void nomeFantasiaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFantasiaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFantasiaTextFieldActionPerformed

    private void logradouroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logradouroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logradouroTextFieldActionPerformed

    private void estadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoTextFieldActionPerformed

    private void cidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeTextFieldActionPerformed

    private void razaoSocialTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaoSocialTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaoSocialTextFieldActionPerformed

    private void cpfFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfFormattedTextFieldFocusLost
        // TODO add your handling code here:   
    }//GEN-LAST:event_cpfFormattedTextFieldFocusLost

    private void nomeClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteTextFieldActionPerformed

    private void telefonePrincipalTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonePrincipalTextFieldKeyTyped
        // TODO add your handling code here:
        char telefonePrinc = evt.getKeyChar();

        if (!((telefonePrincipalTextField.getText().length() <= 10) && (telefonePrinc >= '0') && (telefonePrinc <= '9')
                || (telefonePrinc == KeyEvent.VK_BACK_SPACE)
                || (telefonePrinc == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_telefonePrincipalTextFieldKeyTyped

    private void telefoneOpcionalTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneOpcionalTextFieldKeyTyped
        // TODO add your handling code here:
        char telefoneOpcional = evt.getKeyChar();

        if (!((telefoneOpcionalTextField.getText().length() <= 10) && (telefoneOpcional >= '0') && (telefoneOpcional <= '9')
                || (telefoneOpcional == KeyEvent.VK_BACK_SPACE)
                || (telefoneOpcional == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_telefoneOpcionalTextFieldKeyTyped

    private void numeroTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroTextFieldKeyTyped
        // TODO add your handling code here:
        /*char numero = evt.getKeyChar();

        if (!((numeroTextField.getText().length() <= 10) && (numero >= '0') && (numero <= '9')
                || (numero == KeyEvent.VK_BACK_SPACE)
                || (numero == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }*/
    }//GEN-LAST:event_numeroTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientesForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientesForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientesForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientesForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JToggleButton cadastrarButton;
    private javax.swing.JFormattedTextField cepFormattedTextField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JRadioButton clienteFisicoButton;
    private javax.swing.JFormattedTextField cnpjFormattedTextField;
    private javax.swing.JFormattedTextField cpfFormattedTextField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JTextField estadoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JRadioButton juridicoFisicoButton;
    private javax.swing.JLabel logradouroLabel;
    private javax.swing.JTextField logradouroTextField;
    private javax.swing.JLabel nomeClienteLabel;
    private javax.swing.JTextField nomeClienteTextField;
    private javax.swing.JLabel nomeFantasiaLabel;
    private javax.swing.JTextField nomeFantasiaTextField;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroTextField;
    private javax.swing.JLabel razaoSocialLabel;
    private javax.swing.JTextField razaoSocialTextField;
    private javax.swing.JLabel telefoneOpcionalLabel;
    private javax.swing.JTextField telefoneOpcionalTextField;
    private javax.swing.JLabel telefonePrincipalLabel;
    private javax.swing.JTextField telefonePrincipalTextField;
    private javax.swing.ButtonGroup tipoClienteButton;
    // End of variables declaration//GEN-END:variables
}
