/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque.telas;

import estoque.controladores.ControladorMecanico;
import estoque.modelos.Mecanico;
import estoque.util.Util;
import javax.swing.JOptionPane;

/**
 *
 * @author FHC
 */
public class AlterarMecanicoForm extends javax.swing.JFrame {

    /**
     * Creates new form AlterarMecanicoForm
     */
    
    private String oldCpf;
    Mecanico mec;
    MecanicoListagem formPai;
     
    
    public AlterarMecanicoForm() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    
    public AlterarMecanicoForm(Mecanico mec, MecanicoListagem formPai) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.mec = mec;
        this.formPai = formPai;
        this.carregarCampos(this.mec);
    }

    private void carregarCampos(Mecanico mec) {
        try {
            this.oldCpf = mec.getCpf();
            cpfMecanicoAlterarFormattedTextField.setText(mec.getCpf());
            nomeMecanicoAlterarTextField.setText(mec.getNome());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }
    
    private void limparCampos() {
        try {
            nomeMecanicoAlterarTextField.setText("");
            cpfMecanicoAlterarFormattedTextField.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeMecanicoAlterarTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cpfMecanicoAlterarFormattedTextField = new javax.swing.JFormattedTextField(new Util().mascara("###.###.###-##"));
        limparFormularioMecanicoToggleButton = new javax.swing.JToggleButton();
        alterarMecanicoToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Alterar Mecânico");

        jLabel2.setText("Nome do Mecânico:");

        jLabel3.setText("Cpf:");

        limparFormularioMecanicoToggleButton.setText("Limpar Formulário");
        limparFormularioMecanicoToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparFormularioMecanicoToggleButtonActionPerformed(evt);
            }
        });

        alterarMecanicoToggleButton.setText("Alterar");
        alterarMecanicoToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarMecanicoToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limparFormularioMecanicoToggleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alterarMecanicoToggleButton)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nomeMecanicoAlterarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cpfMecanicoAlterarFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeMecanicoAlterarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpfMecanicoAlterarFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparFormularioMecanicoToggleButton)
                    .addComponent(alterarMecanicoToggleButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparFormularioMecanicoToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparFormularioMecanicoToggleButtonActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_limparFormularioMecanicoToggleButtonActionPerformed

    private void alterarMecanicoToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarMecanicoToggleButtonActionPerformed
        // TODO add your handling code here:
        
        try {
            ControladorMecanico cmec = new ControladorMecanico();

            Mecanico mec = new Mecanico();

            mec.setCpf(cpfMecanicoAlterarFormattedTextField.getText());
            mec.setNome(nomeMecanicoAlterarTextField.getText());

            cmec.atualizar(mec, this.oldCpf);
            JOptionPane.showMessageDialog(rootPane, "Mecânico Atualizado com"
                    + " Sucesso");
            this.formPai.listarMecanico();
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_alterarMecanicoToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarMecanicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarMecanicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarMecanicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarMecanicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarMecanicoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton alterarMecanicoToggleButton;
    private javax.swing.JFormattedTextField cpfMecanicoAlterarFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton limparFormularioMecanicoToggleButton;
    private javax.swing.JTextField nomeMecanicoAlterarTextField;
    // End of variables declaration//GEN-END:variables
}
