/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque.telas;

import estoque.controladores.ControladorClientePessoaJuridica;
import estoque.modelos.ClientePessoaJuridica;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FHC
 */
public class ClientePessoaJuridicaListagem extends javax.swing.JFrame {

    /**
     * Creates new form ClientePessoaJuridicaListagem
     */
    ArrayList<ClientePessoaJuridica> listaClientePessoaJuridicaGlobal;

    public ClientePessoaJuridicaListagem() {
        initComponents();
        this.setLocationRelativeTo(null);

        listar();

    }

    private void listar() {

        DefaultTableModel modelo = new DefaultTableModel();
        //atribuindo as colunas da tabela
        modelo.setColumnIdentifiers(new String[]{"Nome Fantasia", "CNPJ",
            "Razão Social", "Email", "Telefone Principal", "Telefone Opicional"});

        try {
            ControladorClientePessoaJuridica cpj = new ControladorClientePessoaJuridica();
            this.listaClientePessoaJuridicaGlobal = cpj.listarPessoaJuridica();
            for (ClientePessoaJuridica cj : listaClientePessoaJuridicaGlobal) {
                modelo.addRow(new String[]{"" + cj.getNomeFantasia(), cj.getCnpj(),
                    cj.getRazaoSocial(), cj.getEmail(), cj.getTelefonePrinc(),
                    cj.getTelefoneOpc()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        tabelaClientePJTable.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        ListarClientePJLabel = new javax.swing.JLabel();
        filtroFantasiaLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaClientePJTable = new javax.swing.JTable();
        filtroPessoaJuridicaTextField = new javax.swing.JTextField();
        alterarClientePJButton = new javax.swing.JButton();
        removerClientePJButton = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListarClientePJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListarClientePJLabel.setText("Listar Cliente PJ");

        filtroFantasiaLabel.setText("Filtro por nome fantasia");

        tabelaClientePJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaClientePJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientePJTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaClientePJTable);

        filtroPessoaJuridicaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroPessoaJuridicaTextFieldActionPerformed(evt);
            }
        });

        alterarClientePJButton.setText("Alterar");

        removerClientePJButton.setText("Remover");
        removerClientePJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerClientePJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ListarClientePJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(filtroFantasiaLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(filtroPessoaJuridicaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(alterarClientePJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(removerClientePJButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListarClientePJLabel)
                .addGap(18, 18, 18)
                .addComponent(filtroFantasiaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filtroPessoaJuridicaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerClientePJButton)
                    .addComponent(alterarClientePJButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtroPessoaJuridicaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroPessoaJuridicaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroPessoaJuridicaTextFieldActionPerformed

    private void tabelaClientePJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientePJTableMouseClicked
        // TODO add your handling code here:
        try {
            int index = tabelaClientePJTable.getSelectedRow();
            if (index >= 0) {
                ClientePessoaJuridica cpj = this.listaClientePessoaJuridicaGlobal.get(index);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_tabelaClientePJTableMouseClicked

    private void removerClientePJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerClientePJButtonActionPerformed
        // TODO add your handling code here:
        try {
            ControladorClientePessoaJuridica cpj = new ControladorClientePessoaJuridica();
            //Seleciona a linha da coluna.
            int index = tabelaClientePJTable.getSelectedRow();

            if (index >= 0) {
                ClientePessoaJuridica pj = this.listaClientePessoaJuridicaGlobal.get(index);

                try {
                    cpj.remover(pj);
                    JOptionPane.showMessageDialog(rootPane, "Cliente Removido com "
                            + "Sucesso");
                    listar();
                } catch (Exception ex) {
                    System.out.println();
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione um Cliente para"
                        + " Remover");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_removerClientePJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientePessoaJuridicaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientePessoaJuridicaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientePessoaJuridicaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientePessoaJuridicaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientePessoaJuridicaListagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListarClientePJLabel;
    private javax.swing.JButton alterarClientePJButton;
    private javax.swing.JLabel filtroFantasiaLabel;
    private javax.swing.JTextField filtroPessoaJuridicaTextField;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removerClientePJButton;
    private javax.swing.JTable tabelaClientePJTable;
    // End of variables declaration//GEN-END:variables
}
