/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque.telas;

import estoque.controladores.ControladorClienteFisico;
import estoque.controladores.ControladorClientePessoaJuridica;
import estoque.controladores.ControladorFornecedor;
import estoque.modelos.ClienteFisico;
import estoque.modelos.ClientePessoaJuridica;
import estoque.modelos.Fornecedor;
import estoque.util.Util;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author EWalker
 */
public class FornecedorForm extends javax.swing.JFrame {

    /**
     * Creates new form FormGeral
     */
    public FornecedorForm() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    private void limparCampos() {

        nomeFantasiaTextField.setText("");
        razaoSocialTextField.setText("");
        cnpjFormattedTextField.setText("");
        cepFormattedTextField.setText("");
        logradouroTextField.setText("");
        estadoTextField.setText("");
        cidadeTextField.setText("");
        bairroTextField.setText("");
        emailTextField.setText("");
        telefonePrincipalTextField.setText("");
        telefoneOpcionalTextField.setText("");
        responsaveisTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoClienteButton = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        nomeFantasiaLabel = new javax.swing.JLabel();
        nomeFantasiaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cnpjFormattedTextField = new javax.swing.JFormattedTextField(new Util().mascara("##.###.##"
            + "#/####-##"));
    razaoSocialLabel = new javax.swing.JLabel();
    razaoSocialTextField = new javax.swing.JTextField();
    emailLabel = new javax.swing.JLabel();
    emailTextField = new javax.swing.JTextField();
    telefonePrincipalLabel = new javax.swing.JLabel();
    telefonePrincipalTextField = new javax.swing.JTextField();
    telefoneOpcionalTextField = new javax.swing.JTextField();
    telefoneOpcionalLabel = new javax.swing.JLabel();
    cepLabel = new javax.swing.JLabel();
    cepFormattedTextField = new javax.swing.JFormattedTextField(new Util().mascara("#####-###"));
    logradouroTextField = new javax.swing.JTextField();
    logradouroLabel = new javax.swing.JLabel();
    estadoLabel = new javax.swing.JLabel();
    estadoTextField = new javax.swing.JTextField();
    cidadeTextField = new javax.swing.JTextField();
    bairroTextField = new javax.swing.JTextField();
    bairroLabel = new javax.swing.JLabel();
    cadastrarButton = new javax.swing.JToggleButton();
    jToggleButton2 = new javax.swing.JToggleButton();
    Nome = new javax.swing.JLabel();
    responsaveisTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    cidadeLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel2.setText("Cadastrar Fornecedor");

    nomeFantasiaLabel.setText("Nome Fantasia*");

    nomeFantasiaTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nomeFantasiaTextFieldActionPerformed(evt);
        }
    });

    jLabel3.setText("Cnpj*");

    cnpjFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cnpjFormattedTextFieldActionPerformed(evt);
        }
    });

    razaoSocialLabel.setText("Razão Social*");

    razaoSocialTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            razaoSocialTextFieldActionPerformed(evt);
        }
    });

    emailLabel.setText("E-mail*");

    emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            emailTextFieldFocusLost(evt);
        }
    });

    telefonePrincipalLabel.setText("Telefone Principal*");

    telefoneOpcionalLabel.setText("Telefone Opcional");

    cepLabel.setText("Cep*");

    cepFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            cepFormattedTextFieldFocusLost(evt);
        }
    });

    logradouroTextField.setEnabled(false);
    logradouroTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logradouroTextFieldActionPerformed(evt);
        }
    });

    logradouroLabel.setText("Logradouro");

    estadoLabel.setText("Estado");

    estadoTextField.setEnabled(false);
    estadoTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            estadoTextFieldActionPerformed(evt);
        }
    });

    cidadeTextField.setEnabled(false);
    cidadeTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cidadeTextFieldActionPerformed(evt);
        }
    });

    bairroTextField.setEnabled(false);

    bairroLabel.setText("Bairro");

    cadastrarButton.setText("Cadastrar Fornecedor");
    cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarButtonActionPerformed(evt);
        }
    });

    jToggleButton2.setText("Limpar Formulário");
    jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton2ActionPerformed(evt);
        }
    });

    Nome.setText("Nome dos Responsáveis");

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(153, 153, 0));
    jLabel5.setText("* Campos com asterisco são obrigatórios");

    cidadeLabel.setText("Cidade");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(279, 279, 279)
                    .addComponent(jLabel5)
                    .addGap(18, 18, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(razaoSocialLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(razaoSocialTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(nomeFantasiaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cnpjFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telefonePrincipalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefonePrincipalLabel)
                                .addComponent(telefoneOpcionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButton2)
                                .addComponent(emailLabel)
                                .addComponent(telefoneOpcionalLabel)
                                .addComponent(nomeFantasiaLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(logradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cepLabel)
                                .addComponent(logradouroLabel)
                                .addComponent(estadoLabel)
                                .addComponent(bairroLabel)
                                .addComponent(Nome)
                                .addComponent(bairroTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(cidadeTextField)
                                .addComponent(estadoTextField)
                                .addComponent(cepFormattedTextField))
                            .addComponent(cidadeLabel)
                            .addComponent(responsaveisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE))))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(258, 258, 258))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(jLabel2)
            .addGap(104, 104, 104)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nomeFantasiaLabel)
                .addComponent(cepLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nomeFantasiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cepFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(logradouroLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cnpjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(logradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(razaoSocialLabel)
                .addComponent(estadoLabel))
            .addGap(12, 12, 12)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(razaoSocialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(estadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(emailLabel)
                .addComponent(cidadeLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(telefonePrincipalLabel)
                .addComponent(bairroLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(telefonePrincipalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(11, 11, 11)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Nome)
                .addComponent(telefoneOpcionalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(responsaveisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(telefoneOpcionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(47, 47, 47)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(19, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        limparCampos();

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void cepFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepFormattedTextFieldFocusLost
        // TODO add your handling code here:

        String cepTratado = cepFormattedTextField.getText().replace("-", "");
        String url = "http://viacep.com.br/ws/" + cepTratado + "/json/";

        Util e = new Util();
        try {
            JSONObject obj = new JSONObject(e.getHttpGET(url));
            logradouroTextField.setText(obj.getString("logradouro"));
            estadoTextField.setText(obj.getString("uf"));
            cidadeTextField.setText(obj.getString("localidade"));
            bairroTextField.setText((obj.getString("bairro")));

        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Cep inválido, informe outro!");
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_cepFormattedTextFieldFocusLost

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
            
            Fornecedor f = new Fornecedor();

            f.setCnpj(cnpjFormattedTextField.getText());
            f.setNomeFantasia(nomeFantasiaTextField.getText());
            f.setRazaoSocial(razaoSocialTextField.getText());
            f.setEmail(emailTextField.getText());
            f.setTelefonePrincipal(telefonePrincipalTextField.getText());
            f.setTelefoneOpcional(telefoneOpcionalTextField.getText());
            f.setCep(cepFormattedTextField.getText());
            f.setLogradouro(logradouroTextField.getText());
            f.setEstado(estadoTextField.getText());
            f.setCidade(cidadeTextField.getText());
            f.setBairro(bairroTextField.getText());
            f.setNomeResponsaveis(responsaveisTextField.getText());
          
            try {
            ControladorFornecedor cf = new ControladorFornecedor();
          
                cf.cadastrarFornecedor(f);
                JOptionPane.showMessageDialog(rootPane, "Fornecedor"
                        + " Cadastrado");
                limparCampos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }

        
    }//GEN-LAST:event_cadastrarButtonActionPerformed


    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        // TODO add your handling code here:
        String email = emailTextField.getText().toLowerCase();
        emailTextField.setText(email);

    }//GEN-LAST:event_emailTextFieldFocusLost

    private void cnpjFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjFormattedTextFieldActionPerformed

    private void nomeFantasiaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFantasiaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFantasiaTextFieldActionPerformed

    private void logradouroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logradouroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logradouroTextFieldActionPerformed

    private void estadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoTextFieldActionPerformed

    private void cidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeTextFieldActionPerformed

    private void razaoSocialTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaoSocialTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaoSocialTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedorForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedorForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedorForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JToggleButton cadastrarButton;
    private javax.swing.JFormattedTextField cepFormattedTextField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JFormattedTextField cnpjFormattedTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JTextField estadoTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel logradouroLabel;
    private javax.swing.JTextField logradouroTextField;
    private javax.swing.JLabel nomeFantasiaLabel;
    private javax.swing.JTextField nomeFantasiaTextField;
    private javax.swing.JLabel razaoSocialLabel;
    private javax.swing.JTextField razaoSocialTextField;
    private javax.swing.JTextField responsaveisTextField;
    private javax.swing.JLabel telefoneOpcionalLabel;
    private javax.swing.JTextField telefoneOpcionalTextField;
    private javax.swing.JLabel telefonePrincipalLabel;
    private javax.swing.JTextField telefonePrincipalTextField;
    private javax.swing.ButtonGroup tipoClienteButton;
    // End of variables declaration//GEN-END:variables
}
